{"name": "test_11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'a' in 'bcd'", "trace": "self = <test_pytest.test_assert.Test_d object at 0x03F16130>\n\n    def test_11(self):\n    \n>       assert \"a\"  in \"bcd\"   #包含\nE       AssertionError: assert 'a' in 'bcd'\n\ntest_assert.py:31: AssertionError"}, "start": 1666798540175, "stop": 1666798540177, "uuid": "071c09e2-bfb3-4ddc-921f-25ffe0b25424", "historyId": "65eccba48ea1ed48bafeac6339115c57", "testCaseId": "8a3d001c80f8fc2aa3d199d6c2a3076f", "fullName": "test_assert.Test_d#test_11", "labels": [{"name": "suite", "value": "test_assert"}, {"name": "subSuite", "value": "Test_d"}, {"name": "host", "value": "LAPTOP-GID304T1"}, {"name": "thread", "value": "11764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assert"}]}